influxdb:
  image: influxdb:latest
  container_name: ttoi-influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  env_file:
    - 'env.influxdb'
  volumes:
    - /srv/docker/influxdb/data:/var/lib/influxdb

grafana:
  image: grafana/grafana:latest
  container_name: ttoi-grafana
  ports:
    - "3000:3000"
  env_file:
    - 'env.grafana'
  user: "0"
  links:
    - 'influxdb'
  volumes:
    - /srv/docker/grafana/data:/var/lib/grafana

mosquitto:
  image: eclipse-mosquitto:latest
  container_name: ttoi-mosquitto
  ports:
    - "1883:1883"
    - "9001:9001"
  user: "0"
  volumes:
    - ./develop/mosquitto.conf:/mosquitto/config/mosquitto.conf
    - /srv/docker/mosquitto/data:/mosquitto/data
    - /srv/docker/mosquitto/log:/mosquitto/log
